curl -X POST http://localhost:8000/mainpage/api/token/ \
  -H "Content-Type: application/json" \
  -d '{"username": "mkamel", "password": "123456"}'


###

curl -X POST http://localhost:8000/mainpage/api/token/refresh/ \
  -H "Content-Type: application/json" \
  -d '{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTI2Nzc2NywiaWF0IjoxNzQ1MTgxMzY3LCJqdGkiOiI0NWM4NTM5ZDdiOGQ0ZjM5YWNjOThjOWUwYTA3NGNiNSIsInVzZXJfaWQiOjF9.fg9T3nM7mkt1_vqgFR5W-XDrIeGuPnH_HlVy4irC_z0"}'


####

curl -X GET http://localhost:8000/mainpage/profile/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjQxNzAyLCJpYXQiOjE3NDUyNDA4MDIsImp0aSI6ImFiZDhlNDk5ZmMwNzRhNGNiZjVkMTk5YzdiNmE2NzJlIiwidXNlcl9pZCI6MTJ9.x8cMWrUXSc4R5QkYxvhvY8mmgaKIBbPaMiegfRVfcNQ"

###

curl -X GET http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjQxNzAyLCJpYXQiOjE3NDUyNDA4MDIsImp0aSI6ImFiZDhlNDk5ZmMwNzRhNGNiZjVkMTk5YzdiNmE2NzJlIiwidXNlcl9pZCI6MTJ9.x8cMWrUXSc4R5QkYxvhvY8mmgaKIBbPaMiegfRVfcNQ"


###

curl -X POST http://localhost:8000/mainpage/api/register/ \
  -H "Content-Type: application/json" \
  -d '{"username": "nono7", "password": "12bjxhsdv()K3"}'



###

curl -X POST http://localhost:8000/mainpage/api/token/ \
  -H "Content-Type: application/json" \
  -d '{"username": "nono7", "password": "12bjxhsdv()K3"}'

####

curl -X GET http://localhost:8000/mainpage/myprofile/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjQxNzAyLCJpYXQiOjE3NDUyNDA4MDIsImp0aSI6ImFiZDhlNDk5ZmMwNzRhNGNiZjVkMTk5YzdiNmE2NzJlIiwidXNlcl9pZCI6MTJ9.x8cMWrUXSc4R5QkYxvhvY8mmgaKIBbPaMiegfRVfcNQ"

###

curl -X GET http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTkyMjgyLCJpYXQiOjE3NDUxOTE5ODIsImp0aSI6ImUxYjRjZDQyNGE5NzQwZGFiYTU2ZmQ0NTE5OTIwN2ZmIiwidXNlcl9pZCI6MTJ9.2f2GTfYtabBmImeY-NT_vyKUkS2kKcncq1xuj3QqR5E"

###

curl -X POST http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjQxNzAyLCJpYXQiOjE3NDUyNDA4MDIsImp0aSI6ImFiZDhlNDk5ZmMwNzRhNGNiZjVkMTk5YzdiNmE2NzJlIiwidXNlcl9pZCI6MTJ9.x8cMWrUXSc4R5QkYxvhvY8mmgaKIBbPaMiegfRVfcNQ"
  -H "Content-Type: application/json" \
  -d '{"title": "SALAM ALYKOM", "description": "PROJECT FINISHED"}'
