curl -X POST http://localhost:8000/mainpage/api/token/ \
  -H "Content-Type: application/json" \
  -d '{"username": "mkamel", "password": "123456"}'


###

curl -X POST http://localhost:8000/mainpage/api/token/refresh/ \
  -H "Content-Type: application/json" \
  -d '{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTI2Nzc2NywiaWF0IjoxNzQ1MTgxMzY3LCJqdGkiOiI0NWM4NTM5ZDdiOGQ0ZjM5YWNjOThjOWUwYTA3NGNiNSIsInVzZXJfaWQiOjF9.fg9T3nM7mkt1_vqgFR5W-XDrIeGuPnH_HlVy4irC_z0"}'


####

curl -X GET http://localhost:8000/mainpage/profile/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTkyMTc1LCJpYXQiOjE3NDUxOTE4NzUsImp0aSI6IjA2YzFiYTVlNWJkYTQ1OGM4MzA4ZWE4OTk5OWJmNjc2IiwidXNlcl9pZCI6MX0.RMIQzktKwTwsx8G7K70uZ8eDWe-vjak36IHalJ2GvcI"

###

curl -X GET http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTcxNTMzLCJpYXQiOjE3NDUxNzEyMzMsImp0aSI6ImY0OGFiODRiOGM2ZTRjNzA5MGFlMWVlN2VhMWE5NTEwIiwidXNlcl9pZCI6MX0.DVNe8QSDshBeLEEoDMU8bz7GQcyAnQHEt9PjDAsa804"


###

curl -X POST http://localhost:8000/mainpage/api/register/ \
  -H "Content-Type: application/json" \
  -d '{"username": "nono7", "password": "12bjxhsdv()K3"}'



###

curl -X POST http://localhost:8000/mainpage/api/token/ \
  -H "Content-Type: application/json" \
  -d '{"username": "nono7", "password": "12bjxhsdv()K3"}'

####

curl -X GET http://localhost:8000/mainpage/profile/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTkyMjgyLCJpYXQiOjE3NDUxOTE5ODIsImp0aSI6ImUxYjRjZDQyNGE5NzQwZGFiYTU2ZmQ0NTE5OTIwN2ZmIiwidXNlcl9pZCI6MTJ9.2f2GTfYtabBmImeY-NT_vyKUkS2kKcncq1xuj3QqR5E"

###

curl -X GET http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTkyMjgyLCJpYXQiOjE3NDUxOTE5ODIsImp0aSI6ImUxYjRjZDQyNGE5NzQwZGFiYTU2ZmQ0NTE5OTIwN2ZmIiwidXNlcl9pZCI6MTJ9.2f2GTfYtabBmImeY-NT_vyKUkS2kKcncq1xuj3QqR5E"

###

curl -X POST http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MTkzMDU5LCJpYXQiOjE3NDUxOTI3NTksImp0aSI6IjU3MGI4YWQzZjAzYTQ0MmJhOWNmMWMxOWUyYWIyN2IxIiwidXNlcl9pZCI6MTJ9.RzcAoS_V2N6Sq7mGPAAvVCSB9vLss3K0O07FaRERp1o"
  -H "Content-Type: application/json" \
  -d '{"title": "احا", "description": "12bjxhsdv()K3"}'
