curl -X POST http://localhost:8000/mainpage/api/token/ \
  -H "Content-Type: application/json" \
  -d '{"username": "mkamel", "password": "123456"}'


###

curl -X POST http://localhost:8000/mainpage/api/token/refresh/ \
  -H "Content-Type: application/json" \
  -d '{"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTI2Nzc2NywiaWF0IjoxNzQ1MTgxMzY3LCJqdGkiOiI0NWM4NTM5ZDdiOGQ0ZjM5YWNjOThjOWUwYTA3NGNiNSIsInVzZXJfaWQiOjF9.fg9T3nM7mkt1_vqgFR5W-XDrIeGuPnH_HlVy4irC_z0"}'


####

curl -X GET http://localhost:8000/mainpage/profile \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjYxMTE2LCJpYXQiOjE3NDUyNjAyMTYsImp0aSI6ImM3ZDhkZDQ0OWMzMjRkM2I4MGJkYmY5MWFiOGY2YjNmIiwidXNlcl9pZCI6MX0.gKYZ2zdc-w1h427VZPHUZtzpheCJH2OxUj_HzSJbvbk"

###

curl -X GET http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjYxMTE2LCJpYXQiOjE3NDUyNjAyMTYsImp0aSI6ImM3ZDhkZDQ0OWMzMjRkM2I4MGJkYmY5MWFiOGY2YjNmIiwidXNlcl9pZCI6MX0.gKYZ2zdc-w1h427VZPHUZtzpheCJH2OxUj_HzSJbvbk"


###

curl -X POST http://localhost:8000/mainpage/api/register/ \
  -H "Content-Type: application/json" \
  -d '{"username": "nono7", "password": "12bjxhsdv()K3"}'



###

curl -X POST http://localhost:8000/mainpage/api/token/ \
  -H "Content-Type: application/json" \
  -d '{"username": "testuser", "password": "testpass"}'

####

curl -X GET http://localhost:8000/mainpage/myprofile/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjQxNzAyLCJpYXQiOjE3NDUyNDA4MDIsImp0aSI6ImFiZDhlNDk5ZmMwNzRhNGNiZjVkMTk5YzdiNmE2NzJlIiwidXNlcl9pZCI6MTJ9.x8cMWrUXSc4R5QkYxvhvY8mmgaKIBbPaMiegfRVfcNQ"

###

curl -X POST http://localhost:8000/mainpage/task/ \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1MjU2MzUwLCJpYXQiOjE3NDUyNTU0NTAsImp0aSI6IjBhNTIwNTY0NzUzMjQwNWJiOTEwODQzMzk2NDJjY2RmIiwidXNlcl9pZCI6MTN9.93qrZ6yEdA8M9PRmAmBVQGfI7wwBAI1I0RXD-WI2LYM"
  -H "Content-Type: application/json" \
  -d '{"title": "homework", "description": "signals"}'
